// Code generated by agen, DO NOT EDIT.

package api

import (
	"fmt"

	"github.com/NefixEstrada/agen/runtime/broker"
)

// BuildLightsDimAddress builds the "lightsDim" channel address from
// parameters.
// The ID of the streetlight.
func BuildLightsDimAddress(streetlightId string) (string, error) {
	return fmt.Sprintf("smartylighting.streetlights.1.0.action.%s.dim", streetlightId), nil
}

// BuildLightingMeasuredAddress builds the "lightingMeasured" channel address from
// parameters.
// The ID of the streetlight.
func BuildLightingMeasuredAddress(streetlightId string) (string, error) {
	return fmt.Sprintf("smartylighting.streetlights.1.0.event.%s.lighting.measured", streetlightId), nil
}

// BuildLightTurnOffAddress builds the "lightTurnOff" channel address from
// parameters.
// The ID of the streetlight.
func BuildLightTurnOffAddress(streetlightId string) (string, error) {
	return fmt.Sprintf("smartylighting.streetlights.1.0.action.%s.turn.off", streetlightId), nil
}

// BuildLightTurnOnAddress builds the "lightTurnOn" channel address from
// parameters.
// The ID of the streetlight.
func BuildLightTurnOnAddress(streetlightId string) (string, error) {
	return fmt.Sprintf("smartylighting.streetlights.1.0.action.%s.turn.on", streetlightId), nil
}

type (
	optionFunc[C any] func(*C)
)
type clientConfig struct {
	Publisher broker.Publisher
}

// ClientOption is client config option.
type ClientOption interface {
	applyClient(*clientConfig)
}

var _ ClientOption = (optionFunc[clientConfig])(nil)

func (o optionFunc[C]) applyClient(c *C) {
	o(c)
}

func newClientConfig(opts ...ClientOption) clientConfig {
	cfg := clientConfig{}
	for _, opt := range opts {
		opt.applyClient(&cfg)
	}
	return cfg
}

// WithPublisher specifies the runtime Publisher to use.
//
// It is the low-level escape hatch for protocols without a runtime backend
// and for sharing a connection in tests. If none is specified, the client
// wires the backend of the spec protocol itself.
func WithPublisher(publisher broker.Publisher) ClientOption {
	return optionFunc[clientConfig](func(cfg *clientConfig) {
		if publisher != nil {
			cfg.Publisher = publisher
		}
	})
}
