// Code generated by agen, DO NOT EDIT.

package api

// OperationName is the agen operation name
type OperationName = string

const (
	DimLightOperation                OperationName = "dimLight"
	ReceiveLightMeasurementOperation OperationName = "receiveLightMeasurement"
	TurnOffOperation                 OperationName = "turnOff"
	TurnOnOperation                  OperationName = "turnOn"
)
