// Code generated by agen, DO NOT EDIT.

package api

import (
	"time"

	json "github.com/NefixEstrada/agen/runtime/codec"
	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// Encode implements json.Marshaler.
func (s *DimLightPayload) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *DimLightPayload) encodeFields(e *jx.Encoder) {
	{
		if s.Percentage.Set {
			e.FieldStart("percentage")
			s.Percentage.Encode(e)
		}
	}
	{
		if s.SentAt.Set {
			e.FieldStart("sentAt")
			s.SentAt.Encode(e)
		}
	}
}

var jsonFieldsNameOfDimLightPayload = [2]string{
	0: "percentage",
	1: "sentAt",
}

// Decode decodes DimLightPayload from json.
func (s *DimLightPayload) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode DimLightPayload to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "percentage":
			if err := func() error {
				s.Percentage.Reset()
				if err := s.Percentage.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"percentage\"")
			}
		case "sentAt":
			if err := func() error {
				s.SentAt.Reset()
				if err := s.SentAt.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"sentAt\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode DimLightPayload")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *DimLightPayload) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *DimLightPayload) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *LightMeasuredPayload) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *LightMeasuredPayload) encodeFields(e *jx.Encoder) {
	{
		if s.Lumens.Set {
			e.FieldStart("lumens")
			s.Lumens.Encode(e)
		}
	}
	{
		if s.SentAt.Set {
			e.FieldStart("sentAt")
			s.SentAt.Encode(e)
		}
	}
}

var jsonFieldsNameOfLightMeasuredPayload = [2]string{
	0: "lumens",
	1: "sentAt",
}

// Decode decodes LightMeasuredPayload from json.
func (s *LightMeasuredPayload) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode LightMeasuredPayload to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "lumens":
			if err := func() error {
				s.Lumens.Reset()
				if err := s.Lumens.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"lumens\"")
			}
		case "sentAt":
			if err := func() error {
				s.SentAt.Reset()
				if err := s.SentAt.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"sentAt\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode LightMeasuredPayload")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *LightMeasuredPayload) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *LightMeasuredPayload) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes int as json.
func (o OptInt) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Int(int(o.Value))
}

// Decode decodes int from json.
func (o *OptInt) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptInt to nil")
	}
	o.Set = true
	v, err := d.Int()
	if err != nil {
		return err
	}
	o.Value = int(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptInt) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptInt) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes SentAt as json.
func (o OptSentAt) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	o.Value.Encode(e)
}

// Decode decodes SentAt from json.
func (o *OptSentAt) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptSentAt to nil")
	}
	o.Set = true
	if err := o.Value.Decode(d); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptSentAt) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptSentAt) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes TurnOnOffPayloadCommand as json.
func (o OptTurnOnOffPayloadCommand) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes TurnOnOffPayloadCommand from json.
func (o *OptTurnOnOffPayloadCommand) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptTurnOnOffPayloadCommand to nil")
	}
	o.Set = true
	if err := o.Value.Decode(d); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptTurnOnOffPayloadCommand) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptTurnOnOffPayloadCommand) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes SentAt as json.
func (s SentAt) Encode(e *jx.Encoder) {
	unwrapped := time.Time(s)

	json.EncodeDateTime(e, unwrapped)
}

// Decode decodes SentAt from json.
func (s *SentAt) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode SentAt to nil")
	}
	var unwrapped time.Time
	if err := func() error {
		v, err := json.DecodeDateTime(d)
		unwrapped = v
		if err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "alias")
	}
	*s = SentAt(unwrapped)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s SentAt) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *SentAt) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *TurnOnOffPayload) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *TurnOnOffPayload) encodeFields(e *jx.Encoder) {
	{
		if s.Command.Set {
			e.FieldStart("command")
			s.Command.Encode(e)
		}
	}
	{
		if s.SentAt.Set {
			e.FieldStart("sentAt")
			s.SentAt.Encode(e)
		}
	}
}

var jsonFieldsNameOfTurnOnOffPayload = [2]string{
	0: "command",
	1: "sentAt",
}

// Decode decodes TurnOnOffPayload from json.
func (s *TurnOnOffPayload) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode TurnOnOffPayload to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "command":
			if err := func() error {
				s.Command.Reset()
				if err := s.Command.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"command\"")
			}
		case "sentAt":
			if err := func() error {
				s.SentAt.Reset()
				if err := s.SentAt.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"sentAt\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode TurnOnOffPayload")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *TurnOnOffPayload) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *TurnOnOffPayload) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes TurnOnOffPayloadCommand as json.
func (s TurnOnOffPayloadCommand) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes TurnOnOffPayloadCommand from json.
func (s *TurnOnOffPayloadCommand) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode TurnOnOffPayloadCommand to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch TurnOnOffPayloadCommand(v) {
	case TurnOnOffPayloadCommandOn:
		*s = TurnOnOffPayloadCommandOn
	case TurnOnOffPayloadCommandOff:
		*s = TurnOnOffPayloadCommandOff
	default:
		*s = TurnOnOffPayloadCommand(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s TurnOnOffPayloadCommand) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *TurnOnOffPayloadCommand) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}
