// Code generated by agen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
)

// Command a particular streetlight to dim the lights.
type DimLight struct {
	Payload DimLightPayload `json:"-"`
}

// GetPayload returns the value of Payload.
func (s *DimLight) GetPayload() DimLightPayload {
	return s.Payload
}

// SetPayload sets the value of Payload.
func (s *DimLight) SetPayload(val DimLightPayload) {
	s.Payload = val
}

// Ref: #/components/schemas/dimLightPayload
type DimLightPayload struct {
	// Percentage to which the light should be dimmed to.
	Percentage OptInt    `json:"percentage"`
	SentAt     OptSentAt `json:"sentAt"`
}

// GetPercentage returns the value of Percentage.
func (s *DimLightPayload) GetPercentage() OptInt {
	return s.Percentage
}

// GetSentAt returns the value of SentAt.
func (s *DimLightPayload) GetSentAt() OptSentAt {
	return s.SentAt
}

// SetPercentage sets the value of Percentage.
func (s *DimLightPayload) SetPercentage(val OptInt) {
	s.Percentage = val
}

// SetSentAt sets the value of SentAt.
func (s *DimLightPayload) SetSentAt(val OptSentAt) {
	s.SentAt = val
}

// Inform about environmental lighting conditions of a particular streetlight.
type LightMeasured struct {
	Payload LightMeasuredPayload `json:"-"`
}

// GetPayload returns the value of Payload.
func (s *LightMeasured) GetPayload() LightMeasuredPayload {
	return s.Payload
}

// SetPayload sets the value of Payload.
func (s *LightMeasured) SetPayload(val LightMeasuredPayload) {
	s.Payload = val
}

// Ref: #/components/schemas/lightMeasuredPayload
type LightMeasuredPayload struct {
	// Light intensity measured in lumens.
	Lumens OptInt    `json:"lumens"`
	SentAt OptSentAt `json:"sentAt"`
}

// GetLumens returns the value of Lumens.
func (s *LightMeasuredPayload) GetLumens() OptInt {
	return s.Lumens
}

// GetSentAt returns the value of SentAt.
func (s *LightMeasuredPayload) GetSentAt() OptSentAt {
	return s.SentAt
}

// SetLumens sets the value of Lumens.
func (s *LightMeasuredPayload) SetLumens(val OptInt) {
	s.Lumens = val
}

// SetSentAt sets the value of SentAt.
func (s *LightMeasuredPayload) SetSentAt(val OptSentAt) {
	s.SentAt = val
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSentAt returns new OptSentAt with value set to v.
func NewOptSentAt(v SentAt) OptSentAt {
	return OptSentAt{
		Value: v,
		Set:   true,
	}
}

// OptSentAt is optional SentAt.
type OptSentAt struct {
	Value SentAt
	Set   bool
}

// IsSet returns true if OptSentAt was set.
func (o OptSentAt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSentAt) Reset() {
	var v SentAt
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSentAt) SetTo(v SentAt) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSentAt) Get() (v SentAt, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSentAt) Or(d SentAt) SentAt {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTurnOnOffPayloadCommand returns new OptTurnOnOffPayloadCommand with value set to v.
func NewOptTurnOnOffPayloadCommand(v TurnOnOffPayloadCommand) OptTurnOnOffPayloadCommand {
	return OptTurnOnOffPayloadCommand{
		Value: v,
		Set:   true,
	}
}

// OptTurnOnOffPayloadCommand is optional TurnOnOffPayloadCommand.
type OptTurnOnOffPayloadCommand struct {
	Value TurnOnOffPayloadCommand
	Set   bool
}

// IsSet returns true if OptTurnOnOffPayloadCommand was set.
func (o OptTurnOnOffPayloadCommand) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTurnOnOffPayloadCommand) Reset() {
	var v TurnOnOffPayloadCommand
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTurnOnOffPayloadCommand) SetTo(v TurnOnOffPayloadCommand) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTurnOnOffPayloadCommand) Get() (v TurnOnOffPayloadCommand, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTurnOnOffPayloadCommand) Or(d TurnOnOffPayloadCommand) TurnOnOffPayloadCommand {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type SentAt time.Time

// Command a particular streetlight to turn the lights on or off.
type TurnOnOff struct {
	Payload TurnOnOffPayload `json:"-"`
}

// GetPayload returns the value of Payload.
func (s *TurnOnOff) GetPayload() TurnOnOffPayload {
	return s.Payload
}

// SetPayload sets the value of Payload.
func (s *TurnOnOff) SetPayload(val TurnOnOffPayload) {
	s.Payload = val
}

// Ref: #/components/schemas/turnOnOffPayload
type TurnOnOffPayload struct {
	// Whether to turn on or off the light.
	Command OptTurnOnOffPayloadCommand `json:"command"`
	SentAt  OptSentAt                  `json:"sentAt"`
}

// GetCommand returns the value of Command.
func (s *TurnOnOffPayload) GetCommand() OptTurnOnOffPayloadCommand {
	return s.Command
}

// GetSentAt returns the value of SentAt.
func (s *TurnOnOffPayload) GetSentAt() OptSentAt {
	return s.SentAt
}

// SetCommand sets the value of Command.
func (s *TurnOnOffPayload) SetCommand(val OptTurnOnOffPayloadCommand) {
	s.Command = val
}

// SetSentAt sets the value of SentAt.
func (s *TurnOnOffPayload) SetSentAt(val OptSentAt) {
	s.SentAt = val
}

// Whether to turn on or off the light.
type TurnOnOffPayloadCommand string

const (
	TurnOnOffPayloadCommandOn  TurnOnOffPayloadCommand = "on"
	TurnOnOffPayloadCommandOff TurnOnOffPayloadCommand = "off"
)

// AllValues returns all TurnOnOffPayloadCommand values.
func (TurnOnOffPayloadCommand) AllValues() []TurnOnOffPayloadCommand {
	return []TurnOnOffPayloadCommand{
		TurnOnOffPayloadCommandOn,
		TurnOnOffPayloadCommandOff,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TurnOnOffPayloadCommand) MarshalText() ([]byte, error) {
	switch s {
	case TurnOnOffPayloadCommandOn:
		return []byte(s), nil
	case TurnOnOffPayloadCommandOff:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TurnOnOffPayloadCommand) UnmarshalText(data []byte) error {
	switch TurnOnOffPayloadCommand(data) {
	case TurnOnOffPayloadCommandOn:
		*s = TurnOnOffPayloadCommandOn
		return nil
	case TurnOnOffPayloadCommandOff:
		*s = TurnOnOffPayloadCommandOff
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
