// Code generated by agen, DO NOT EDIT.

package api

import (
	"context"

	"github.com/NefixEstrada/agen/runtime/agenerrors"
)

// UnimplementedHandler returns agenerrors.ErrNotImplemented for every receive
// operation. Useful during development: embed it and implement operations
// incrementally.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

func (UnimplementedHandler) ReceiveLightMeasurement(ctx context.Context, msg *LightMeasured) error {
	return agenerrors.ErrNotImplemented
}
