// Code generated by agen, DO NOT EDIT.

package api

import (
	"context"

	"github.com/NefixEstrada/agen/runtime/broker"
)

// publishConfig carries options applied on top of a generated message.
type publishConfig struct {
	key     string
	headers map[string]string
}

// PublishOption customizes a single publish.
type PublishOption func(*publishConfig)

func newPublishConfig() *publishConfig {
	return &publishConfig{
		headers: map[string]string{},
	}
}

// WithKey sets the broker partition key of the published message.
func WithKey(key string) PublishOption {
	return func(c *publishConfig) {
		c.key = key
	}
}

// WithHeader sets an extra header on the published message.
func WithHeader(k, v string) PublishOption {
	return func(c *publishConfig) {
		c.headers[k] = v
	}
}

// Client publishes messages of the application's `send` operations to a
// broker via a runtime Publisher.
type Client struct {
	publisher broker.Publisher
}

// NewClient creates a Client publishing with the given Publisher.
func NewClient(publisher broker.Publisher) *Client {
	return &Client{
		publisher: publisher,
	}
}

// Close closes the underlying publisher.
func (c *Client) Close(ctx context.Context) error {
	return c.publisher.Close(ctx)
}

// DimLight publishes a message of the "dimLight" operation.
func (c *Client) DimLight(ctx context.Context, streetlightId string, msg *DimLight, opts ...PublishOption) error {
	topic, err := BuildLightsDimAddress(streetlightId)
	if err != nil {
		return err
	}
	out, err := encodeDimLightMessage(topic, msg, opts...)
	if err != nil {
		return err
	}
	return c.publisher.Publish(ctx, out)
}

// TurnOff publishes a message of the "turnOff" operation.
func (c *Client) TurnOff(ctx context.Context, streetlightId string, msg *TurnOnOff, opts ...PublishOption) error {
	topic, err := BuildLightTurnOffAddress(streetlightId)
	if err != nil {
		return err
	}
	out, err := encodeTurnOffMessage(topic, msg, opts...)
	if err != nil {
		return err
	}
	return c.publisher.Publish(ctx, out)
}

// TurnOn publishes a message of the "turnOn" operation.
func (c *Client) TurnOn(ctx context.Context, streetlightId string, msg *TurnOnOff, opts ...PublishOption) error {
	topic, err := BuildLightTurnOnAddress(streetlightId)
	if err != nil {
		return err
	}
	out, err := encodeTurnOnMessage(topic, msg, opts...)
	if err != nil {
		return err
	}
	return c.publisher.Publish(ctx, out)
}
