// Code generated by agen, DO NOT EDIT.

package api

// serverConst is a constant server address from the AsyncAPI document.
type serverConst string

// MtlsMinusConnectionsServer is the address of the "mtls-connections" server. Protocol: kafka-secure.
// Test broker secured with X509
const MtlsMinusConnectionsServer serverConst = "test.mykafkacluster.org:28092"

// ScramMinusConnectionsServer is the address of the "scram-connections" server. Protocol: kafka-secure.
// Test broker secured with scramSha256
const ScramMinusConnectionsServer serverConst = "test.mykafkacluster.org:18092"

// Build returns the server address.
func (s serverConst) Build() (string, error) {
	return string(s), nil
}

// MustBuild is like Build, but panics on error. It never errors for constant
// servers; it is kept for interface parity.
func (s serverConst) MustBuild() string {
	addr, err := s.Build()
	if err != nil {
		panic(err)
	}
	return addr
}
