// Code generated by agen, DO NOT EDIT.

package api

import (
	"github.com/NefixEstrada/agen/runtime/agenerrors"
	"github.com/NefixEstrada/agen/runtime/broker"
	"github.com/go-faster/jx"
)

func encodeDimLightMessage(topic string, msg *DimLight, opts ...PublishOption) (broker.Outgoing, error) {
	if err := msg.Validate(); err != nil {
		return broker.Outgoing{}, &agenerrors.ValidateMessageError{
			Operation: "dimLight",
			Message:   "dimLight",
			Err:       err,
		}
	}
	cfg := newPublishConfig()
	for _, opt := range opts {
		opt(cfg)
	}
	out := broker.Outgoing{
		Topic:       topic,
		Key:         cfg.key,
		ContentType: "application/json",
		Headers:     cfg.headers,
	}
	{
		var e jx.Encoder
		msg.Payload.Encode(&e)
		out.Body = e.Bytes()
	}
	return out, nil
}
func decodeReceiveLightMeasurementMessage(raw broker.Incoming) (*LightMeasured, error) {
	msg := new(LightMeasured)
	{
		d := jx.DecodeBytes(raw.Body())
		if err := msg.Payload.Decode(d); err != nil {
			return nil, &agenerrors.DecodeMessageError{
				Operation: "receiveLightMeasurement",
				Message:   "lightMeasured",
				Err:       err,
			}
		}
	}
	if err := msg.Validate(); err != nil {
		return nil, &agenerrors.ValidateMessageError{
			Operation: "receiveLightMeasurement",
			Message:   "lightMeasured",
			Err:       err,
		}
	}
	return msg, nil
}
func encodeTurnOffMessage(topic string, msg *TurnOnOff, opts ...PublishOption) (broker.Outgoing, error) {
	if err := msg.Validate(); err != nil {
		return broker.Outgoing{}, &agenerrors.ValidateMessageError{
			Operation: "turnOff",
			Message:   "turnOnOff",
			Err:       err,
		}
	}
	cfg := newPublishConfig()
	for _, opt := range opts {
		opt(cfg)
	}
	out := broker.Outgoing{
		Topic:       topic,
		Key:         cfg.key,
		ContentType: "application/json",
		Headers:     cfg.headers,
	}
	{
		var e jx.Encoder
		msg.Payload.Encode(&e)
		out.Body = e.Bytes()
	}
	return out, nil
}
func encodeTurnOnMessage(topic string, msg *TurnOnOff, opts ...PublishOption) (broker.Outgoing, error) {
	if err := msg.Validate(); err != nil {
		return broker.Outgoing{}, &agenerrors.ValidateMessageError{
			Operation: "turnOn",
			Message:   "turnOnOff",
			Err:       err,
		}
	}
	cfg := newPublishConfig()
	for _, opt := range opts {
		opt(cfg)
	}
	out := broker.Outgoing{
		Topic:       topic,
		Key:         cfg.key,
		ContentType: "application/json",
		Headers:     cfg.headers,
	}
	{
		var e jx.Encoder
		msg.Payload.Encode(&e)
		out.Body = e.Bytes()
	}
	return out, nil
}
