// Code generated by agen, DO NOT EDIT.

package orders

// serverConst is a constant server address from the AsyncAPI document.
type serverConst string

// ProductionServer is the address of the "production" server. Protocol: redis.
const ProductionServer serverConst = "redis.example.io:6379"

// Build returns the server address.
func (s serverConst) Build() (string, error) {
	return string(s), nil
}

// MustBuild is like Build, but panics on error. It never errors for constant
// servers; it is kept for interface parity.
func (s serverConst) MustBuild() string {
	addr, err := s.Build()
	if err != nil {
		panic(err)
	}
	return addr
}
