// Code generated by agen, DO NOT EDIT.

package orders

import (
	"fmt"

	"github.com/NefixEstrada/agen/runtime/broker"
)

// BuildOrderEventsAddress builds the "orderEvents" channel address from
// parameters.
// The tenant identifier.
func BuildOrderEventsAddress(tenantId string) (string, error) {
	switch tenantId {
	case "acme", "globex":
	default:
		return "", fmt.Errorf("invalid tenantId: must be one of %q", "acme, globex")
	}
	return fmt.Sprintf("orders.events.%s", tenantId), nil
}

type (
	optionFunc[C any] func(*C)
)

type serverConfig struct {
	Addr       string
	Addresses  []string
	Middleware []Middleware
}

// ServerOption is server config option.
type ServerOption interface {
	applyServer(*serverConfig)
}

var _ ServerOption = (optionFunc[serverConfig])(nil)

func (o optionFunc[C]) applyServer(c *C) {
	o(c)
}

func newServerConfig(opts ...ServerOption) serverConfig {
	cfg := serverConfig{}
	for _, opt := range opts {
		opt.applyServer(&cfg)
	}
	return cfg
}

// addr returns the broker address: WithAddr when set, else the first spec
// server.
func (cfg serverConfig) addr() string {
	if cfg.Addr != "" {
		return cfg.Addr
	}
	return string(ProductionServer)
}

// addresses returns the addresses to consume: WithAddresses when set, else
// the static addresses of the receive channels.
func (cfg serverConfig) addresses() []string {
	if len(cfg.Addresses) > 0 {
		return cfg.Addresses
	}
	return []string{}
}

type clientConfig struct {
	Publisher broker.Publisher
}

// ClientOption is client config option.
type ClientOption interface {
	applyClient(*clientConfig)
}

var _ ClientOption = (optionFunc[clientConfig])(nil)

func (o optionFunc[C]) applyClient(c *C) {
	o(c)
}

func newClientConfig(opts ...ClientOption) clientConfig {
	cfg := clientConfig{}
	for _, opt := range opts {
		opt.applyClient(&cfg)
	}
	return cfg
}

// Option is config option.
type Option interface {
	ServerOption
	ClientOption
}

// WithPublisher specifies the runtime Publisher to use.
//
// It is the low-level escape hatch for protocols without a runtime backend
// and for sharing a connection in tests. If none is specified, the client
// wires the backend of the spec protocol itself.
func WithPublisher(publisher broker.Publisher) ClientOption {
	return optionFunc[clientConfig](func(cfg *clientConfig) {
		if publisher != nil {
			cfg.Publisher = publisher
		}
	})
}

// WithAddr sets the broker address of the server; by default the first
// server of the AsyncAPI document.
func WithAddr(addr string) ServerOption {
	return optionFunc[serverConfig](func(cfg *serverConfig) {
		if addr != "" {
			cfg.Addr = addr
		}
	})
}

// WithAddresses sets the addresses (streams, channels or glob patterns) to
// consume, overriding the static addresses of the receive channels.
func WithAddresses(addresses ...string) ServerOption {
	return optionFunc[serverConfig](func(cfg *serverConfig) {
		if len(addresses) > 0 {
			cfg.Addresses = append(cfg.Addresses, addresses...)
		}
	})
}

// WithMiddleware adds middlewares to the subscriber dispatch chain; the
// first middleware is the outermost.
func WithMiddleware(mw ...Middleware) ServerOption {
	return optionFunc[serverConfig](func(cfg *serverConfig) {
		if len(mw) > 0 {
			cfg.Middleware = append(cfg.Middleware, mw...)
		}
	})
}
