// Code generated by agen, DO NOT EDIT.

package orders

// OperationName is the agen operation name
type OperationName = string

const (
	ReceiveOrderEventsOperation OperationName = "receiveOrderEvents"
	SendOrderEventsOperation    OperationName = "sendOrderEvents"
)
