// Code generated by agen, DO NOT EDIT.

package orders

import (
	"context"
)

// ReceiveOrderEvents handles the "receiveOrderEvents" operation.
//
// The message arrives from the "orders.events.{tenantId}" address.
type ReceiveOrderEventsHandler interface {
	ReceiveOrderEvents(ctx context.Context, msg OrderEventsMessage) error
}

// Handler handles all receive operations of the application.
type Handler interface {
	ReceiveOrderEvents(ctx context.Context, msg OrderEventsMessage) error
}

// SubscriberHandlers collects the handler of every receive operation.
type SubscriberHandlers struct {
	ReceiveOrderEvents ReceiveOrderEventsHandler
}

// NewSubscriberHandlers builds SubscriberHandlers from per-operation handlers.
func NewSubscriberHandlers(
	h0 ReceiveOrderEventsHandler,
) *SubscriberHandlers {
	return &SubscriberHandlers{
		ReceiveOrderEvents: h0,
	}
}

// NewHandler builds SubscriberHandlers from a single Handler implementing
// every receive operation.
func NewHandler(h Handler) *SubscriberHandlers {
	return &SubscriberHandlers{
		ReceiveOrderEvents: h,
	}
}
