// Code generated by agen, DO NOT EDIT.

package orders

import (
	"context"
	"sync"

	"github.com/NefixEstrada/agen/runtime/broker"
)

// FakePublisher is a broker.Publisher that captures outgoing messages in
// memory; use it to unit-test publishing code without a broker.
type FakePublisher struct {
	mu       sync.Mutex
	Messages []broker.Outgoing
	Err      error // returned by Publish when set
}

var _ broker.Publisher = (*FakePublisher)(nil)

// Publish implements broker.Publisher.
func (p *FakePublisher) Publish(ctx context.Context, out broker.Outgoing) error {
	p.mu.Lock()
	defer p.mu.Unlock()
	if p.Err != nil {
		return p.Err
	}
	p.Messages = append(p.Messages, out)
	return nil
}

// Close implements broker.Publisher.
func (p *FakePublisher) Close(ctx context.Context) error { return nil }

// Reset drops captured messages.
func (p *FakePublisher) Reset() {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.Messages = nil
}

// FakeReceiveOrderEventsHandler captures ReceiveOrderEvents messages; Err, when set, is
// returned by the handler.
type FakeReceiveOrderEventsHandler struct {
	mu       sync.Mutex
	Messages []OrderEventsMessage
	Err      error
}

var _ ReceiveOrderEventsHandler = (*FakeReceiveOrderEventsHandler)(nil)

// ReceiveOrderEvents implements ReceiveOrderEventsHandler.
func (h *FakeReceiveOrderEventsHandler) ReceiveOrderEvents(ctx context.Context, msg OrderEventsMessage) error {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.Err != nil {
		return h.Err
	}
	h.Messages = append(h.Messages, msg)
	return nil
}
