// Code generated by agen, DO NOT EDIT.

package orders

import (
	"time"
)

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type OrderCancelled struct {
	Payload OrderCancelledPayload `json:"-"`
}

// GetPayload returns the value of Payload.
func (s *OrderCancelled) GetPayload() OrderCancelledPayload {
	return s.Payload
}

// SetPayload sets the value of Payload.
func (s *OrderCancelled) SetPayload(val OrderCancelledPayload) {
	s.Payload = val
}

func (*OrderCancelled) orderEventsMessage() {}

type OrderCancelledPayload struct {
	OrderId string    `json:"orderId"`
	Reason  OptString `json:"reason"`
}

// GetOrderId returns the value of OrderId.
func (s *OrderCancelledPayload) GetOrderId() string {
	return s.OrderId
}

// GetReason returns the value of Reason.
func (s *OrderCancelledPayload) GetReason() OptString {
	return s.Reason
}

// SetOrderId sets the value of OrderId.
func (s *OrderCancelledPayload) SetOrderId(val string) {
	s.OrderId = val
}

// SetReason sets the value of Reason.
func (s *OrderCancelledPayload) SetReason(val OptString) {
	s.Reason = val
}

type OrderCreated struct {
	Payload OrderCreatedPayload `json:"-"`
}

// GetPayload returns the value of Payload.
func (s *OrderCreated) GetPayload() OrderCreatedPayload {
	return s.Payload
}

// SetPayload sets the value of Payload.
func (s *OrderCreated) SetPayload(val OrderCreatedPayload) {
	s.Payload = val
}

func (*OrderCreated) orderEventsMessage() {}

type OrderCreatedPayload struct {
	OrderId   string      `json:"orderId"`
	CreatedAt OptDateTime `json:"createdAt"`
}

// GetOrderId returns the value of OrderId.
func (s *OrderCreatedPayload) GetOrderId() string {
	return s.OrderId
}

// GetCreatedAt returns the value of CreatedAt.
func (s *OrderCreatedPayload) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// SetOrderId sets the value of OrderId.
func (s *OrderCreatedPayload) SetOrderId(val string) {
	s.OrderId = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *OrderCreatedPayload) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}
