// Code generated by agen, DO NOT EDIT.

package orders

import (
	"fmt"
)

// BuildOrderEventsAddress builds the "orderEvents" channel address from
// parameters.
// The tenant identifier.
func BuildOrderEventsAddress(tenantId string) (string, error) {
	switch tenantId {
	case "acme", "globex":
	default:
		return "", fmt.Errorf("invalid tenantId: must be one of %q", "acme, globex")
	}
	return fmt.Sprintf("orders.events.%s", tenantId), nil
}

// ServerInfo describes a spec server entry.
type ServerInfo struct {
	Name            string
	Host            string
	Protocol        string
	ProtocolVersion string
}

// Spec servers, from the AsyncAPI document.
var Servers = []ServerInfo{
	{
		Name:     "production",
		Host:     "redis.example.io:6379",
		Protocol: "redis",
	},
}
