// Code generated by agen, DO NOT EDIT.

package orders

import (
	"github.com/NefixEstrada/agen/runtime/agenerrors"
	"github.com/NefixEstrada/agen/runtime/broker"
	"github.com/go-faster/jx"
)

func decodeReceiveOrderEventsOrderCancelled(raw broker.Incoming) (*OrderCancelled, error) {
	msg := new(OrderCancelled)
	{
		d := jx.DecodeBytes(raw.Body())
		if err := msg.Payload.Decode(d); err != nil {
			return nil, err
		}
	}
	return msg, nil
}
func decodeReceiveOrderEventsOrderCreated(raw broker.Incoming) (*OrderCreated, error) {
	msg := new(OrderCreated)
	{
		d := jx.DecodeBytes(raw.Body())
		if err := msg.Payload.Decode(d); err != nil {
			return nil, err
		}
	}
	return msg, nil
}
func decodeReceiveOrderEventsMessage(raw broker.Incoming) (OrderEventsMessage, error) {
	{
		msg, err := decodeReceiveOrderEventsOrderCancelled(raw)
		if err == nil {
			return msg, nil
		}
	}
	{
		msg, err := decodeReceiveOrderEventsOrderCreated(raw)
		if err == nil {
			return msg, nil
		}
	}
	return nil, &agenerrors.NotDispatchedError{
		Operation:   "receiveOrderEvents",
		ContentType: raw.ContentType(),
	}
}
func encodeSendOrderEventsMessage(topic string, msg OrderEventsMessage, opts ...PublishOption) (broker.Outgoing, error) {
	if m, ok := msg.(*OrderCancelled); ok {
		return encodeSendOrderEventsOrderCancelled(topic, m, opts...)
	}
	if m, ok := msg.(*OrderCreated); ok {
		return encodeSendOrderEventsOrderCreated(topic, m, opts...)
	}
	return broker.Outgoing{}, &agenerrors.NotDispatchedError{
		Operation:   "sendOrderEvents",
		ContentType: "",
	}
}
func encodeSendOrderEventsOrderCancelled(topic string, msg *OrderCancelled, opts ...PublishOption) (broker.Outgoing, error) {
	cfg := newPublishConfig()
	for _, opt := range opts {
		opt(cfg)
	}
	out := broker.Outgoing{
		Topic:       topic,
		Key:         cfg.key,
		ContentType: "application/json",
		Headers:     cfg.headers,
	}
	{
		var e jx.Encoder
		msg.Payload.Encode(&e)
		out.Body = e.Bytes()
	}
	return out, nil
}
func encodeSendOrderEventsOrderCreated(topic string, msg *OrderCreated, opts ...PublishOption) (broker.Outgoing, error) {
	cfg := newPublishConfig()
	for _, opt := range opts {
		opt(cfg)
	}
	out := broker.Outgoing{
		Topic:       topic,
		Key:         cfg.key,
		ContentType: "application/json",
		Headers:     cfg.headers,
	}
	{
		var e jx.Encoder
		msg.Payload.Encode(&e)
		out.Body = e.Bytes()
	}
	return out, nil
}
