// Code generated by agen, DO NOT EDIT.

package streetlightskafka

import (
	"fmt"
)

// BuildLightsDimAddress builds the "lightsDim" channel address from
// parameters.
// The ID of the streetlight.
func BuildLightsDimAddress(streetlightId string) (string, error) {
	return fmt.Sprintf("smartylighting.streetlights.1.0.action.%s.dim", streetlightId), nil
}

// BuildLightingMeasuredAddress builds the "lightingMeasured" channel address from
// parameters.
// The ID of the streetlight.
func BuildLightingMeasuredAddress(streetlightId string) (string, error) {
	return fmt.Sprintf("smartylighting.streetlights.1.0.event.%s.lighting.measured", streetlightId), nil
}

// BuildLightTurnOffAddress builds the "lightTurnOff" channel address from
// parameters.
// The ID of the streetlight.
func BuildLightTurnOffAddress(streetlightId string) (string, error) {
	return fmt.Sprintf("smartylighting.streetlights.1.0.action.%s.turn.off", streetlightId), nil
}

// BuildLightTurnOnAddress builds the "lightTurnOn" channel address from
// parameters.
// The ID of the streetlight.
func BuildLightTurnOnAddress(streetlightId string) (string, error) {
	return fmt.Sprintf("smartylighting.streetlights.1.0.action.%s.turn.on", streetlightId), nil
}

// ServerInfo describes a spec server entry.
type ServerInfo struct {
	Name            string
	Host            string
	Protocol        string
	ProtocolVersion string
}

// Spec servers, from the AsyncAPI document.
var Servers = []ServerInfo{
	{
		Name:     "mtls-connections",
		Host:     "test.mykafkacluster.org:28092",
		Protocol: "kafka-secure",
	},
	{
		Name:     "scram-connections",
		Host:     "test.mykafkacluster.org:18092",
		Protocol: "kafka-secure",
	},
}
