// Code generated by agen, DO NOT EDIT.

package streetlightskafka

import (
	"context"
)

// Inform about environmental lighting conditions of a particular streetlight.
//
// The message arrives from the "smartylighting.streetlights.1.0.event.{streetlightId}.lighting.measured" address.
type ReceiveLightMeasurementHandler interface {
	ReceiveLightMeasurement(ctx context.Context, msg *LightMeasured) error
}

// Handler handles all receive operations of the application.
type Handler interface {
	ReceiveLightMeasurement(ctx context.Context, msg *LightMeasured) error
}

// SubscriberHandlers collects the handler of every receive operation.
type SubscriberHandlers struct {
	ReceiveLightMeasurement ReceiveLightMeasurementHandler
}

// NewSubscriberHandlers builds SubscriberHandlers from per-operation handlers.
func NewSubscriberHandlers(
	h0 ReceiveLightMeasurementHandler,
) *SubscriberHandlers {
	return &SubscriberHandlers{
		ReceiveLightMeasurement: h0,
	}
}

// NewHandler builds SubscriberHandlers from a single Handler implementing
// every receive operation.
func NewHandler(h Handler) *SubscriberHandlers {
	return &SubscriberHandlers{
		ReceiveLightMeasurement: h,
	}
}
