// Code generated by agen, DO NOT EDIT.

package streetlightssub

import (
	"time"

	"github.com/go-faster/errors"
)

type LightCommand struct {
	Payload LightCommandPayload `json:"-"`
}

// GetPayload returns the value of Payload.
func (s *LightCommand) GetPayload() LightCommandPayload {
	return s.Payload
}

// SetPayload sets the value of Payload.
func (s *LightCommand) SetPayload(val LightCommandPayload) {
	s.Payload = val
}

// Ref: #/components/schemas/lightCommandPayload
type LightCommandPayload struct {
	Command OptLightCommandPayloadCommand `json:"command"`
}

// GetCommand returns the value of Command.
func (s *LightCommandPayload) GetCommand() OptLightCommandPayloadCommand {
	return s.Command
}

// SetCommand sets the value of Command.
func (s *LightCommandPayload) SetCommand(val OptLightCommandPayloadCommand) {
	s.Command = val
}

type LightCommandPayloadCommand string

const (
	LightCommandPayloadCommandOn  LightCommandPayloadCommand = "on"
	LightCommandPayloadCommandOff LightCommandPayloadCommand = "off"
)

// AllValues returns all LightCommandPayloadCommand values.
func (LightCommandPayloadCommand) AllValues() []LightCommandPayloadCommand {
	return []LightCommandPayloadCommand{
		LightCommandPayloadCommandOn,
		LightCommandPayloadCommandOff,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s LightCommandPayloadCommand) MarshalText() ([]byte, error) {
	switch s {
	case LightCommandPayloadCommandOn:
		return []byte(s), nil
	case LightCommandPayloadCommandOff:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *LightCommandPayloadCommand) UnmarshalText(data []byte) error {
	switch LightCommandPayloadCommand(data) {
	case LightCommandPayloadCommandOn:
		*s = LightCommandPayloadCommandOn
		return nil
	case LightCommandPayloadCommandOff:
		*s = LightCommandPayloadCommandOff
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type LightMeasured struct {
	Payload LightMeasuredPayload `json:"-"`
	Headers LightMeasuredHeaders `json:"-"`
}

// GetPayload returns the value of Payload.
func (s *LightMeasured) GetPayload() LightMeasuredPayload {
	return s.Payload
}

// GetHeaders returns the value of Headers.
func (s *LightMeasured) GetHeaders() LightMeasuredHeaders {
	return s.Headers
}

// SetPayload sets the value of Payload.
func (s *LightMeasured) SetPayload(val LightMeasuredPayload) {
	s.Payload = val
}

// SetHeaders sets the value of Headers.
func (s *LightMeasured) SetHeaders(val LightMeasuredHeaders) {
	s.Headers = val
}

// Ref: #/components/schemas/lightMeasuredHeaders
type LightMeasuredHeaders struct {
	RequestId OptString `json:"requestId"`
}

// GetRequestId returns the value of RequestId.
func (s *LightMeasuredHeaders) GetRequestId() OptString {
	return s.RequestId
}

// SetRequestId sets the value of RequestId.
func (s *LightMeasuredHeaders) SetRequestId(val OptString) {
	s.RequestId = val
}

// Ref: #/components/schemas/lightMeasuredPayload
type LightMeasuredPayload struct {
	Lumens OptInt      `json:"lumens"`
	SentAt OptDateTime `json:"sentAt"`
}

// GetLumens returns the value of Lumens.
func (s *LightMeasuredPayload) GetLumens() OptInt {
	return s.Lumens
}

// GetSentAt returns the value of SentAt.
func (s *LightMeasuredPayload) GetSentAt() OptDateTime {
	return s.SentAt
}

// SetLumens sets the value of Lumens.
func (s *LightMeasuredPayload) SetLumens(val OptInt) {
	s.Lumens = val
}

// SetSentAt sets the value of SentAt.
func (s *LightMeasuredPayload) SetSentAt(val OptDateTime) {
	s.SentAt = val
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptLightCommandPayloadCommand returns new OptLightCommandPayloadCommand with value set to v.
func NewOptLightCommandPayloadCommand(v LightCommandPayloadCommand) OptLightCommandPayloadCommand {
	return OptLightCommandPayloadCommand{
		Value: v,
		Set:   true,
	}
}

// OptLightCommandPayloadCommand is optional LightCommandPayloadCommand.
type OptLightCommandPayloadCommand struct {
	Value LightCommandPayloadCommand
	Set   bool
}

// IsSet returns true if OptLightCommandPayloadCommand was set.
func (o OptLightCommandPayloadCommand) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptLightCommandPayloadCommand) Reset() {
	var v LightCommandPayloadCommand
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptLightCommandPayloadCommand) SetTo(v LightCommandPayloadCommand) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptLightCommandPayloadCommand) Get() (v LightCommandPayloadCommand, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptLightCommandPayloadCommand) Or(d LightCommandPayloadCommand) LightCommandPayloadCommand {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
