// Code generated by agen, DO NOT EDIT.

package streetlightssub

import (
	"github.com/NefixEstrada/agen/runtime/agenerrors"
	"github.com/NefixEstrada/agen/runtime/broker"
	"github.com/go-faster/jx"
)

func decodeReceiveLightMeasurementMessage(raw broker.Incoming) (*LightMeasured, error) {
	msg := new(LightMeasured)
	{
		hdrs := make(map[string]string, len(raw.HeaderNames()))
		for _, name := range raw.HeaderNames() {
			hdrs[name] = raw.Header(name)
		}
		d := jx.DecodeBytes(broker.HeadersToJSON(hdrs))
		if err := msg.Headers.Decode(d); err != nil {
			return nil, &agenerrors.DecodeMessageError{
				Operation: "receiveLightMeasurement",
				Message:   "lightMeasured",
				Err:       err,
			}
		}
	}
	{
		d := jx.DecodeBytes(raw.Body())
		if err := msg.Payload.Decode(d); err != nil {
			return nil, &agenerrors.DecodeMessageError{
				Operation: "receiveLightMeasurement",
				Message:   "lightMeasured",
				Err:       err,
			}
		}
	}
	return msg, nil
}
