// Code generated by agen, DO NOT EDIT.

package streetlightssub

import (
	"fmt"
)

// BuildLightMeasuredAddress builds the "lightMeasured" channel address from
// parameters.
// The ID of the streetlight.
func BuildLightMeasuredAddress(streetlightId string) (string, error) {
	switch streetlightId {
	case "1", "2", "3":
	default:
		return "", fmt.Errorf("invalid streetlightId: must be one of %q", "1, 2, 3")
	}
	return fmt.Sprintf("streetlights.%s.light", streetlightId), nil
}

// LightCommandAddress is the static address of the "lightCommand" channel.
const LightCommandAddress = "streetlights.command"

// ServerInfo describes a spec server entry.
type ServerInfo struct {
	Name            string
	Host            string
	Protocol        string
	ProtocolVersion string
}

// Spec servers, from the AsyncAPI document.
var Servers = []ServerInfo{
	{
		Name:     "production",
		Host:     "redis.example.io:6379",
		Protocol: "redis",
	},
}
