// Code generated by agen, DO NOT EDIT.

package redisdemo

import (
	"time"

	"github.com/go-faster/errors"
)

type LightCommand struct {
	Payload LightCommandPayload `json:"-"`
}

// GetPayload returns the value of Payload.
func (s *LightCommand) GetPayload() LightCommandPayload {
	return s.Payload
}

// SetPayload sets the value of Payload.
func (s *LightCommand) SetPayload(val LightCommandPayload) {
	s.Payload = val
}

type LightCommandPayload struct {
	Command LightCommandPayloadCommand `json:"command"`
	SentAt  time.Time                  `json:"sentAt"`
}

// GetCommand returns the value of Command.
func (s *LightCommandPayload) GetCommand() LightCommandPayloadCommand {
	return s.Command
}

// GetSentAt returns the value of SentAt.
func (s *LightCommandPayload) GetSentAt() time.Time {
	return s.SentAt
}

// SetCommand sets the value of Command.
func (s *LightCommandPayload) SetCommand(val LightCommandPayloadCommand) {
	s.Command = val
}

// SetSentAt sets the value of SentAt.
func (s *LightCommandPayload) SetSentAt(val time.Time) {
	s.SentAt = val
}

type LightCommandPayloadCommand string

const (
	LightCommandPayloadCommandOn  LightCommandPayloadCommand = "on"
	LightCommandPayloadCommandOff LightCommandPayloadCommand = "off"
)

// AllValues returns all LightCommandPayloadCommand values.
func (LightCommandPayloadCommand) AllValues() []LightCommandPayloadCommand {
	return []LightCommandPayloadCommand{
		LightCommandPayloadCommandOn,
		LightCommandPayloadCommandOff,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s LightCommandPayloadCommand) MarshalText() ([]byte, error) {
	switch s {
	case LightCommandPayloadCommandOn:
		return []byte(s), nil
	case LightCommandPayloadCommandOff:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *LightCommandPayloadCommand) UnmarshalText(data []byte) error {
	switch LightCommandPayloadCommand(data) {
	case LightCommandPayloadCommandOn:
		*s = LightCommandPayloadCommandOn
		return nil
	case LightCommandPayloadCommandOff:
		*s = LightCommandPayloadCommandOff
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
