// Code generated by agen, DO NOT EDIT.

package redisdemo

// LightCommandAddress is the static address of the "lightCommand" channel.
const LightCommandAddress = "streetlights.command"

// ServerInfo describes a spec server entry.
type ServerInfo struct {
	Name            string
	Host            string
	Protocol        string
	ProtocolVersion string
}

// Spec servers, from the AsyncAPI document.
var Servers = []ServerInfo{
	{
		Name:     "local",
		Host:     "localhost:6379",
		Protocol: "redis",
	},
}
