// Code generated by agen, DO NOT EDIT.

package redisdemo

import (
	"context"
)

// Receive light commands (demo consumer).
//
// The message arrives from the "streetlights.command" address.
type ReceiveLightCommandHandler interface {
	ReceiveLightCommand(ctx context.Context, msg *LightCommand) error
}

// Handler handles all receive operations of the application.
type Handler interface {
	ReceiveLightCommand(ctx context.Context, msg *LightCommand) error
}

// SubscriberHandlers collects the handler of every receive operation.
type SubscriberHandlers struct {
	ReceiveLightCommand ReceiveLightCommandHandler
}

// NewSubscriberHandlers builds SubscriberHandlers from per-operation handlers.
func NewSubscriberHandlers(
	h0 ReceiveLightCommandHandler,
) *SubscriberHandlers {
	return &SubscriberHandlers{
		ReceiveLightCommand: h0,
	}
}

// NewHandler builds SubscriberHandlers from a single Handler implementing
// every receive operation.
func NewHandler(h Handler) *SubscriberHandlers {
	return &SubscriberHandlers{
		ReceiveLightCommand: h,
	}
}
