// Code generated by agen, DO NOT EDIT.

package redisdemo

import (
	"math/bits"
	"strconv"

	json "github.com/NefixEstrada/agen/runtime/codec"
	validate "github.com/NefixEstrada/agen/runtime/validate"
	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// Encode implements json.Marshaler.
func (s *LightCommandPayload) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *LightCommandPayload) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("command")
		s.Command.Encode(e)
	}
	{
		e.FieldStart("sentAt")
		json.EncodeDateTime(e, s.SentAt)
	}
}

var jsonFieldsNameOfLightCommandPayload = [2]string{
	0: "command",
	1: "sentAt",
}

// Decode decodes LightCommandPayload from json.
func (s *LightCommandPayload) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode LightCommandPayload to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "command":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				if err := s.Command.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"command\"")
			}
		case "sentAt":
			requiredBitSet[0] |= 1 << 1
			if err := func() error {
				v, err := json.DecodeDateTime(d)
				s.SentAt = v
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"sentAt\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode LightCommandPayload")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000011,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfLightCommandPayload) {
					name = jsonFieldsNameOfLightCommandPayload[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *LightCommandPayload) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *LightCommandPayload) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes LightCommandPayloadCommand as json.
func (s LightCommandPayloadCommand) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes LightCommandPayloadCommand from json.
func (s *LightCommandPayloadCommand) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode LightCommandPayloadCommand to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch LightCommandPayloadCommand(v) {
	case LightCommandPayloadCommandOn:
		*s = LightCommandPayloadCommandOn
	case LightCommandPayloadCommandOff:
		*s = LightCommandPayloadCommandOff
	default:
		*s = LightCommandPayloadCommand(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s LightCommandPayloadCommand) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *LightCommandPayloadCommand) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}
