// Code generated by agen, DO NOT EDIT.

package streetlightspub

import (
	"fmt"

	"github.com/NefixEstrada/agen/runtime/broker"
	redisruntime "github.com/NefixEstrada/agen/runtime/redis"
)

// BuildLightMeasuredAddress builds the "lightMeasured" channel address from
// parameters.
// The ID of the streetlight.
func BuildLightMeasuredAddress(streetlightId string) (string, error) {
	switch streetlightId {
	case "1", "2", "3":
	default:
		return "", fmt.Errorf("invalid streetlightId: must be one of %q", "1, 2, 3")
	}
	return fmt.Sprintf("streetlights.%s.light", streetlightId), nil
}

// LightCommandAddress is the static address of the "lightCommand" channel.
const LightCommandAddress = "streetlights.command"

type (
	optionFunc[C any] func(*C)
)

// Mode selects the broker mapping used by the generated client and server
// (redis: streams or pubsub, see runtime/redis).
type Mode = redisruntime.Mode

// Supported broker mapping modes.
const (
	// ModeStreams is the durable at-least-once mapping (default).
	ModeStreams = redisruntime.ModeStreams
	// ModePubSub is the fire-and-forget mapping.
	ModePubSub = redisruntime.ModePubSub
)

// modeOption sets the broker mapping mode on every config that has one.
type modeOption struct{ mode Mode }

func (o modeOption) applyClient(c *clientConfig) { c.Mode = o.mode }

type clientConfig struct {
	Publisher broker.Publisher
	Mode      Mode
}

// ClientOption is client config option.
type ClientOption interface {
	applyClient(*clientConfig)
}

var _ ClientOption = (optionFunc[clientConfig])(nil)

func (o optionFunc[C]) applyClient(c *C) {
	o(c)
}

func newClientConfig(opts ...ClientOption) clientConfig {
	cfg := clientConfig{}
	for _, opt := range opts {
		opt.applyClient(&cfg)
	}
	return cfg
}

// WithPublisher specifies the runtime Publisher to use.
//
// It is the low-level escape hatch for protocols without a runtime backend
// and for sharing a connection in tests. If none is specified, the client
// wires the backend of the spec protocol itself.
func WithPublisher(publisher broker.Publisher) ClientOption {
	return optionFunc[clientConfig](func(cfg *clientConfig) {
		if publisher != nil {
			cfg.Publisher = publisher
		}
	})
}

// WithMode sets the broker mapping mode (streams by default; pubsub for
// fire-and-forget).
func WithMode(mode Mode) ClientOption {
	return modeOption{mode: mode}
}
