// Code generated by agen, DO NOT EDIT.

package streetlightspub

import (
	"context"

	"github.com/NefixEstrada/agen/runtime/broker"
	redisruntime "github.com/NefixEstrada/agen/runtime/redis"
)

// publishConfig carries options applied on top of a generated message.
type publishConfig struct {
	key     string
	headers map[string]string
}

// PublishOption customizes a single publish.
type PublishOption func(*publishConfig)

func newPublishConfig() *publishConfig {
	return &publishConfig{
		headers: map[string]string{},
	}
}

// WithKey sets the broker partition key of the published message.
func WithKey(key string) PublishOption {
	return func(c *publishConfig) {
		c.key = key
	}
}

// WithHeader sets an extra header on the published message.
func WithHeader(k, v string) PublishOption {
	return func(c *publishConfig) {
		c.headers[k] = v
	}
}

// Client publishes messages of the application's `send` operations to a
// broker.
type Client struct {
	publisher broker.Publisher
}

// NewClient creates new Client defined by AAS, wiring the runtime publisher
// of the spec protocol.
//
// Pass WithPublisher to reuse an existing runtime Publisher instead.
func NewClient(addr string, opts ...ClientOption) (*Client, error) {
	cfg := newClientConfig(opts...)
	publisher := cfg.Publisher
	if publisher == nil {
		p, err := redisruntime.NewPublisher(redisruntime.PublisherConfig{
			Addr: addr,
			Mode: cfg.Mode,
		})
		if err != nil {
			return nil, err
		}
		publisher = p
	}
	return &Client{
		publisher: publisher,
	}, nil
}

// Close closes the underlying publisher.
func (c *Client) Close(ctx context.Context) error {
	return c.publisher.Close(ctx)
}

// SendLightCommand publishes a message of the "sendLightCommand" operation.
func (c *Client) SendLightCommand(ctx context.Context, msg *LightCommand, opts ...PublishOption) error {
	topic := LightCommandAddress
	out, err := encodeSendLightCommandMessage(topic, msg, opts...)
	if err != nil {
		return err
	}
	return c.publisher.Publish(ctx, out)
}
