// Code generated by agen, DO NOT EDIT.

package api

// OperationName is the agen operation name
type OperationName = string

const (
	LightMeasuredOperation      OperationName = "lightMeasured"
	TurnOnDotPublishOperation   OperationName = "turnOn.publish"
	TurnOnDotSubscribeOperation OperationName = "turnOn.subscribe"
)
