// Code generated by agen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
)

type CustomMessageId struct {
	Payload CustomMessageIdPayload `json:"-"`
}

// GetPayload returns the value of Payload.
func (s *CustomMessageId) GetPayload() CustomMessageIdPayload {
	return s.Payload
}

// SetPayload sets the value of Payload.
func (s *CustomMessageId) SetPayload(val CustomMessageIdPayload) {
	s.Payload = val
}

func (*CustomMessageId) turnOnMessage() {}

type CustomMessageIdPayload struct {
	SomeProperty     OptString                       `json:"someProperty"`
	CircularProperty *MessagesCustomMessageIdPayload `json:"circularProperty"`
}

// GetSomeProperty returns the value of SomeProperty.
func (s *CustomMessageIdPayload) GetSomeProperty() OptString {
	return s.SomeProperty
}

// GetCircularProperty returns the value of CircularProperty.
func (s *CustomMessageIdPayload) GetCircularProperty() *MessagesCustomMessageIdPayload {
	return s.CircularProperty
}

// SetSomeProperty sets the value of SomeProperty.
func (s *CustomMessageIdPayload) SetSomeProperty(val OptString) {
	s.SomeProperty = val
}

// SetCircularProperty sets the value of CircularProperty.
func (s *CustomMessageIdPayload) SetCircularProperty(val *MessagesCustomMessageIdPayload) {
	s.CircularProperty = val
}

type LightMeasuredDotMessage struct {
	Payload LightMeasuredDotMessagePayload `json:"-"`
}

// GetPayload returns the value of Payload.
func (s *LightMeasuredDotMessage) GetPayload() LightMeasuredDotMessagePayload {
	return s.Payload
}

// SetPayload sets the value of Payload.
func (s *LightMeasuredDotMessage) SetPayload(val LightMeasuredDotMessagePayload) {
	s.Payload = val
}

type LightMeasuredDotMessagePayload struct {
	SomeProperty     OptString                    `json:"someProperty"`
	CircularProperty *LightMeasuredMessagePayload `json:"circularProperty"`
}

// GetSomeProperty returns the value of SomeProperty.
func (s *LightMeasuredDotMessagePayload) GetSomeProperty() OptString {
	return s.SomeProperty
}

// GetCircularProperty returns the value of CircularProperty.
func (s *LightMeasuredDotMessagePayload) GetCircularProperty() *LightMeasuredMessagePayload {
	return s.CircularProperty
}

// SetSomeProperty sets the value of SomeProperty.
func (s *LightMeasuredDotMessagePayload) SetSomeProperty(val OptString) {
	s.SomeProperty = val
}

// SetCircularProperty sets the value of CircularProperty.
func (s *LightMeasuredDotMessagePayload) SetCircularProperty(val *LightMeasuredMessagePayload) {
	s.CircularProperty = val
}

// Ref: #/channels/lightingMeasured/messages/lightMeasured.message/payload
type LightMeasuredMessagePayload struct {
	SomeProperty     OptString                    `json:"someProperty"`
	CircularProperty *LightMeasuredMessagePayload `json:"circularProperty"`
}

// GetSomeProperty returns the value of SomeProperty.
func (s *LightMeasuredMessagePayload) GetSomeProperty() OptString {
	return s.SomeProperty
}

// GetCircularProperty returns the value of CircularProperty.
func (s *LightMeasuredMessagePayload) GetCircularProperty() *LightMeasuredMessagePayload {
	return s.CircularProperty
}

// SetSomeProperty sets the value of SomeProperty.
func (s *LightMeasuredMessagePayload) SetSomeProperty(val OptString) {
	s.SomeProperty = val
}

// SetCircularProperty sets the value of CircularProperty.
func (s *LightMeasuredMessagePayload) SetCircularProperty(val *LightMeasuredMessagePayload) {
	s.CircularProperty = val
}

// Ref: #/channels/turnOn/messages/customMessageId/payload
type MessagesCustomMessageIdPayload struct {
	SomeProperty     OptString                       `json:"someProperty"`
	CircularProperty *MessagesCustomMessageIdPayload `json:"circularProperty"`
}

// GetSomeProperty returns the value of SomeProperty.
func (s *MessagesCustomMessageIdPayload) GetSomeProperty() OptString {
	return s.SomeProperty
}

// GetCircularProperty returns the value of CircularProperty.
func (s *MessagesCustomMessageIdPayload) GetCircularProperty() *MessagesCustomMessageIdPayload {
	return s.CircularProperty
}

// SetSomeProperty sets the value of SomeProperty.
func (s *MessagesCustomMessageIdPayload) SetSomeProperty(val OptString) {
	s.SomeProperty = val
}

// SetCircularProperty sets the value of CircularProperty.
func (s *MessagesCustomMessageIdPayload) SetCircularProperty(val *MessagesCustomMessageIdPayload) {
	s.CircularProperty = val
}

// NewOptLightMeasuredMessagePayload returns new OptLightMeasuredMessagePayload with value set to v.
func NewOptLightMeasuredMessagePayload(v LightMeasuredMessagePayload) OptLightMeasuredMessagePayload {
	return OptLightMeasuredMessagePayload{
		Value: v,
		Set:   true,
	}
}

// OptLightMeasuredMessagePayload is optional LightMeasuredMessagePayload.
type OptLightMeasuredMessagePayload struct {
	Value LightMeasuredMessagePayload
	Set   bool
}

// IsSet returns true if OptLightMeasuredMessagePayload was set.
func (o OptLightMeasuredMessagePayload) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptLightMeasuredMessagePayload) Reset() {
	var v LightMeasuredMessagePayload
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptLightMeasuredMessagePayload) SetTo(v LightMeasuredMessagePayload) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptLightMeasuredMessagePayload) Get() (v LightMeasuredMessagePayload, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptLightMeasuredMessagePayload) Or(d LightMeasuredMessagePayload) LightMeasuredMessagePayload {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMessagesCustomMessageIdPayload returns new OptMessagesCustomMessageIdPayload with value set to v.
func NewOptMessagesCustomMessageIdPayload(v MessagesCustomMessageIdPayload) OptMessagesCustomMessageIdPayload {
	return OptMessagesCustomMessageIdPayload{
		Value: v,
		Set:   true,
	}
}

// OptMessagesCustomMessageIdPayload is optional MessagesCustomMessageIdPayload.
type OptMessagesCustomMessageIdPayload struct {
	Value MessagesCustomMessageIdPayload
	Set   bool
}

// IsSet returns true if OptMessagesCustomMessageIdPayload was set.
func (o OptMessagesCustomMessageIdPayload) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMessagesCustomMessageIdPayload) Reset() {
	var v MessagesCustomMessageIdPayload
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMessagesCustomMessageIdPayload) SetTo(v MessagesCustomMessageIdPayload) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMessagesCustomMessageIdPayload) Get() (v MessagesCustomMessageIdPayload, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMessagesCustomMessageIdPayload) Or(d MessagesCustomMessageIdPayload) MessagesCustomMessageIdPayload {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSentAt returns new OptSentAt with value set to v.
func NewOptSentAt(v SentAt) OptSentAt {
	return OptSentAt{
		Value: v,
		Set:   true,
	}
}

// OptSentAt is optional SentAt.
type OptSentAt struct {
	Value SentAt
	Set   bool
}

// IsSet returns true if OptSentAt was set.
func (o OptSentAt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSentAt) Reset() {
	var v SentAt
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSentAt) SetTo(v SentAt) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSentAt) Get() (v SentAt, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSentAt) Or(d SentAt) SentAt {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTurnOnOffPayloadCommand returns new OptTurnOnOffPayloadCommand with value set to v.
func NewOptTurnOnOffPayloadCommand(v TurnOnOffPayloadCommand) OptTurnOnOffPayloadCommand {
	return OptTurnOnOffPayloadCommand{
		Value: v,
		Set:   true,
	}
}

// OptTurnOnOffPayloadCommand is optional TurnOnOffPayloadCommand.
type OptTurnOnOffPayloadCommand struct {
	Value TurnOnOffPayloadCommand
	Set   bool
}

// IsSet returns true if OptTurnOnOffPayloadCommand was set.
func (o OptTurnOnOffPayloadCommand) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTurnOnOffPayloadCommand) Reset() {
	var v TurnOnOffPayloadCommand
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTurnOnOffPayloadCommand) SetTo(v TurnOnOffPayloadCommand) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTurnOnOffPayloadCommand) Get() (v TurnOnOffPayloadCommand, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTurnOnOffPayloadCommand) Or(d TurnOnOffPayloadCommand) TurnOnOffPayloadCommand {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type SentAt time.Time

// Command a particular streetlight to turn the lights on or off.
type TurnOnOff struct {
	Payload TurnOnOffPayload `json:"-"`
}

// GetPayload returns the value of Payload.
func (s *TurnOnOff) GetPayload() TurnOnOffPayload {
	return s.Payload
}

// SetPayload sets the value of Payload.
func (s *TurnOnOff) SetPayload(val TurnOnOffPayload) {
	s.Payload = val
}

func (*TurnOnOff) turnOnMessage() {}

// Ref: #/components/schemas/turnOnOffPayload
type TurnOnOffPayload struct {
	// Whether to turn on or off the light.
	Command OptTurnOnOffPayloadCommand `json:"command"`
	SentAt  OptSentAt                  `json:"sentAt"`
}

// GetCommand returns the value of Command.
func (s *TurnOnOffPayload) GetCommand() OptTurnOnOffPayloadCommand {
	return s.Command
}

// GetSentAt returns the value of SentAt.
func (s *TurnOnOffPayload) GetSentAt() OptSentAt {
	return s.SentAt
}

// SetCommand sets the value of Command.
func (s *TurnOnOffPayload) SetCommand(val OptTurnOnOffPayloadCommand) {
	s.Command = val
}

// SetSentAt sets the value of SentAt.
func (s *TurnOnOffPayload) SetSentAt(val OptSentAt) {
	s.SentAt = val
}

// Whether to turn on or off the light.
type TurnOnOffPayloadCommand string

const (
	TurnOnOffPayloadCommandOn  TurnOnOffPayloadCommand = "on"
	TurnOnOffPayloadCommandOff TurnOnOffPayloadCommand = "off"
)

// AllValues returns all TurnOnOffPayloadCommand values.
func (TurnOnOffPayloadCommand) AllValues() []TurnOnOffPayloadCommand {
	return []TurnOnOffPayloadCommand{
		TurnOnOffPayloadCommandOn,
		TurnOnOffPayloadCommandOff,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TurnOnOffPayloadCommand) MarshalText() ([]byte, error) {
	switch s {
	case TurnOnOffPayloadCommandOn:
		return []byte(s), nil
	case TurnOnOffPayloadCommandOff:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TurnOnOffPayloadCommand) UnmarshalText(data []byte) error {
	switch TurnOnOffPayloadCommand(data) {
	case TurnOnOffPayloadCommandOn:
		*s = TurnOnOffPayloadCommandOn
		return nil
	case TurnOnOffPayloadCommandOff:
		*s = TurnOnOffPayloadCommandOff
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
