// Code generated by agen, DO NOT EDIT.

package api

import (
	"github.com/NefixEstrada/agen/runtime/agenerrors"
	"github.com/NefixEstrada/agen/runtime/broker"
	"github.com/go-faster/jx"
)

func decodeLightMeasuredMessage(raw broker.Incoming) (*LightMeasuredDotMessage, error) {
	msg := new(LightMeasuredDotMessage)
	{
		d := jx.DecodeBytes(raw.Body())
		if err := msg.Payload.Decode(d); err != nil {
			return nil, &agenerrors.DecodeMessageError{
				Operation: "lightMeasured",
				Message:   "lightMeasured.message",
				Err:       err,
			}
		}
	}
	return msg, nil
}
func decodeTurnOnDotPublishMessage(raw broker.Incoming) (*TurnOnOff, error) {
	msg := new(TurnOnOff)
	{
		d := jx.DecodeBytes(raw.Body())
		if err := msg.Payload.Decode(d); err != nil {
			return nil, &agenerrors.DecodeMessageError{
				Operation: "turnOn.publish",
				Message:   "turnOnOff",
				Err:       err,
			}
		}
	}
	if err := msg.Validate(); err != nil {
		return nil, &agenerrors.ValidateMessageError{
			Operation: "turnOn.publish",
			Message:   "turnOnOff",
			Err:       err,
		}
	}
	return msg, nil
}
func encodeTurnOnDotSubscribeMessage(topic string, msg TurnOnMessage, opts ...PublishOption) (broker.Outgoing, error) {
	if m, ok := msg.(*TurnOnOff); ok {
		return encodeTurnOnDotSubscribeTurnOnOff(topic, m, opts...)
	}
	if m, ok := msg.(*CustomMessageId); ok {
		return encodeTurnOnDotSubscribeCustomMessageId(topic, m, opts...)
	}
	return broker.Outgoing{}, &agenerrors.NotDispatchedError{
		Operation:   "turnOn.subscribe",
		ContentType: "",
	}
}
func encodeTurnOnDotSubscribeTurnOnOff(topic string, msg *TurnOnOff, opts ...PublishOption) (broker.Outgoing, error) {
	if err := msg.Validate(); err != nil {
		return broker.Outgoing{}, &agenerrors.ValidateMessageError{
			Operation: "turnOn.subscribe",
			Message:   "turnOnOff",
			Err:       err,
		}
	}
	cfg := newPublishConfig()
	for _, opt := range opts {
		opt(cfg)
	}
	out := broker.Outgoing{
		Topic:       topic,
		Key:         cfg.key,
		ContentType: "application/json",
		Headers:     cfg.headers,
	}
	{
		var e jx.Encoder
		msg.Payload.Encode(&e)
		out.Body = e.Bytes()
	}
	return out, nil
}
func encodeTurnOnDotSubscribeCustomMessageId(topic string, msg *CustomMessageId, opts ...PublishOption) (broker.Outgoing, error) {
	cfg := newPublishConfig()
	for _, opt := range opts {
		opt(cfg)
	}
	out := broker.Outgoing{
		Topic:       topic,
		Key:         cfg.key,
		ContentType: "application/json",
		Headers:     cfg.headers,
	}
	{
		var e jx.Encoder
		msg.Payload.Encode(&e)
		out.Body = e.Bytes()
	}
	return out, nil
}
