// Code generated by agen, DO NOT EDIT.

package convertedstreetlights

// LightingMeasuredAddress is the static address of the "lightingMeasured" channel.
const LightingMeasuredAddress = "lightingMeasured"

// TurnOnAddress is the static address of the "turnOn" channel.
const TurnOnAddress = "turnOn"
