// Code generated by agen, DO NOT EDIT.

package api

import (
	"context"

	"github.com/NefixEstrada/agen/runtime/agenerrors"
	"github.com/NefixEstrada/agen/runtime/broker"
	"github.com/go-faster/errors"
)

// Subscriber dispatches raw incoming messages to typed handlers: decode,
// validate, dispatch. It implements broker.Dispatcher.
type Subscriber struct {
	handlers *SubscriberHandlers
	dispatch broker.Handler
}

// NewSubscriber creates a Subscriber, wrapping the dispatch chain with the
// given middlewares (applied left to right: the first middleware is the
// outermost).
func NewSubscriber(handlers *SubscriberHandlers, middleware ...broker.Middleware) *Subscriber {
	s := &Subscriber{
		handlers: handlers,
		dispatch: nil,
	}
	s.dispatch = broker.Chain(middleware...)(s.dispatchMessage)
	return s
}

// Handlers returns the subscriber handlers.
func (s *Subscriber) Handlers() *SubscriberHandlers {
	return s.handlers
}

// Dispatch implements broker.Dispatcher: it decodes the raw message for the
// matching receive operation, validates it and calls the typed handler.
//
// The raw topic is matched against static channel addresses first; operations
// on parameterized channels (or with multiple messages) are tried in order.
func (s *Subscriber) Dispatch(ctx context.Context, raw broker.Incoming) error {
	return s.dispatch(ctx, raw)
}

func (s *Subscriber) dispatchMessage(ctx context.Context, raw broker.Incoming) error {
	switch {
	case raw.Topic() == LightingMeasuredAddress:
		return s.dispatchLightMeasured(ctx, raw)
	case raw.Topic() == TurnOnAddress:
		return s.dispatchTurnOnDotPublish(ctx, raw)
	default:
		{
			err := s.dispatchLightMeasured(ctx, raw)
			if !errors.Is(err, errSkipOperation) {
				return err
			}
		}
		{
			err := s.dispatchTurnOnDotPublish(ctx, raw)
			if !errors.Is(err, errSkipOperation) {
				return err
			}
		}
		return &agenerrors.NotDispatchedError{
			Operation:   "",
			ContentType: raw.ContentType(),
		}
	}
}

func (s *Subscriber) dispatchLightMeasured(ctx context.Context, raw broker.Incoming) error {
	msg, err := decodeLightMeasuredMessage(raw)
	if err != nil {
		var notDispatched *agenerrors.NotDispatchedError
		if errors.As(err, &notDispatched) {
			return errSkipOperation
		}
		return err
	}
	if err := s.handlers.LightMeasured.LightMeasured(ctx, msg); err != nil {
		return err
	}
	return raw.Ack()
}

func (s *Subscriber) dispatchTurnOnDotPublish(ctx context.Context, raw broker.Incoming) error {
	msg, err := decodeTurnOnDotPublishMessage(raw)
	if err != nil {
		var notDispatched *agenerrors.NotDispatchedError
		if errors.As(err, &notDispatched) {
			return errSkipOperation
		}
		return err
	}
	if err := s.handlers.TurnOnDotPublish.TurnOnDotPublish(ctx, msg); err != nil {
		return err
	}
	return raw.Ack()
}

// errSkipOperation signals that a message did not match an operation; used
// internally when routing by trial decode.
var errSkipOperation = errors.New("skip operation")
