// Code generated by agen, DO NOT EDIT.

package convertedstreetlights

import (
	"time"

	json "github.com/NefixEstrada/agen/runtime/codec"
	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// Encode implements json.Marshaler.
func (s *CustomMessageIdPayload) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *CustomMessageIdPayload) encodeFields(e *jx.Encoder) {
	{
		if s.SomeProperty.Set {
			e.FieldStart("someProperty")
			s.SomeProperty.Encode(e)
		}
	}
	{
		if s.CircularProperty != nil {
			e.FieldStart("circularProperty")
			s.CircularProperty.Encode(e)
		}
	}
}

var jsonFieldsNameOfCustomMessageIdPayload = [2]string{
	0: "someProperty",
	1: "circularProperty",
}

// Decode decodes CustomMessageIdPayload from json.
func (s *CustomMessageIdPayload) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode CustomMessageIdPayload to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "someProperty":
			if err := func() error {
				s.SomeProperty.Reset()
				if err := s.SomeProperty.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"someProperty\"")
			}
		case "circularProperty":
			if err := func() error {
				s.CircularProperty = nil
				var elem MessagesCustomMessageIdPayload
				if err := elem.Decode(d); err != nil {
					return err
				}
				s.CircularProperty = &elem
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"circularProperty\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode CustomMessageIdPayload")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *CustomMessageIdPayload) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *CustomMessageIdPayload) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *LightMeasuredDotMessagePayload) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *LightMeasuredDotMessagePayload) encodeFields(e *jx.Encoder) {
	{
		if s.SomeProperty.Set {
			e.FieldStart("someProperty")
			s.SomeProperty.Encode(e)
		}
	}
	{
		if s.CircularProperty != nil {
			e.FieldStart("circularProperty")
			s.CircularProperty.Encode(e)
		}
	}
}

var jsonFieldsNameOfLightMeasuredDotMessagePayload = [2]string{
	0: "someProperty",
	1: "circularProperty",
}

// Decode decodes LightMeasuredDotMessagePayload from json.
func (s *LightMeasuredDotMessagePayload) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode LightMeasuredDotMessagePayload to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "someProperty":
			if err := func() error {
				s.SomeProperty.Reset()
				if err := s.SomeProperty.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"someProperty\"")
			}
		case "circularProperty":
			if err := func() error {
				s.CircularProperty = nil
				var elem LightMeasuredMessagePayload
				if err := elem.Decode(d); err != nil {
					return err
				}
				s.CircularProperty = &elem
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"circularProperty\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode LightMeasuredDotMessagePayload")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *LightMeasuredDotMessagePayload) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *LightMeasuredDotMessagePayload) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *LightMeasuredMessagePayload) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *LightMeasuredMessagePayload) encodeFields(e *jx.Encoder) {
	{
		if s.SomeProperty.Set {
			e.FieldStart("someProperty")
			s.SomeProperty.Encode(e)
		}
	}
	{
		if s.CircularProperty != nil {
			e.FieldStart("circularProperty")
			s.CircularProperty.Encode(e)
		}
	}
}

var jsonFieldsNameOfLightMeasuredMessagePayload = [2]string{
	0: "someProperty",
	1: "circularProperty",
}

// Decode decodes LightMeasuredMessagePayload from json.
func (s *LightMeasuredMessagePayload) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode LightMeasuredMessagePayload to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "someProperty":
			if err := func() error {
				s.SomeProperty.Reset()
				if err := s.SomeProperty.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"someProperty\"")
			}
		case "circularProperty":
			if err := func() error {
				s.CircularProperty = nil
				var elem LightMeasuredMessagePayload
				if err := elem.Decode(d); err != nil {
					return err
				}
				s.CircularProperty = &elem
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"circularProperty\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode LightMeasuredMessagePayload")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *LightMeasuredMessagePayload) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *LightMeasuredMessagePayload) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *MessagesCustomMessageIdPayload) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *MessagesCustomMessageIdPayload) encodeFields(e *jx.Encoder) {
	{
		if s.SomeProperty.Set {
			e.FieldStart("someProperty")
			s.SomeProperty.Encode(e)
		}
	}
	{
		if s.CircularProperty != nil {
			e.FieldStart("circularProperty")
			s.CircularProperty.Encode(e)
		}
	}
}

var jsonFieldsNameOfMessagesCustomMessageIdPayload = [2]string{
	0: "someProperty",
	1: "circularProperty",
}

// Decode decodes MessagesCustomMessageIdPayload from json.
func (s *MessagesCustomMessageIdPayload) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode MessagesCustomMessageIdPayload to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "someProperty":
			if err := func() error {
				s.SomeProperty.Reset()
				if err := s.SomeProperty.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"someProperty\"")
			}
		case "circularProperty":
			if err := func() error {
				s.CircularProperty = nil
				var elem MessagesCustomMessageIdPayload
				if err := elem.Decode(d); err != nil {
					return err
				}
				s.CircularProperty = &elem
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"circularProperty\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode MessagesCustomMessageIdPayload")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *MessagesCustomMessageIdPayload) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *MessagesCustomMessageIdPayload) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes SentAt as json.
func (o OptSentAt) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	o.Value.Encode(e)
}

// Decode decodes SentAt from json.
func (o *OptSentAt) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptSentAt to nil")
	}
	o.Set = true
	if err := o.Value.Decode(d); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptSentAt) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptSentAt) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes string as json.
func (o OptString) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes string from json.
func (o *OptString) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptString to nil")
	}
	o.Set = true
	v, err := d.Str()
	if err != nil {
		return err
	}
	o.Value = string(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptString) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptString) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes TurnOnOffPayloadCommand as json.
func (o OptTurnOnOffPayloadCommand) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes TurnOnOffPayloadCommand from json.
func (o *OptTurnOnOffPayloadCommand) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptTurnOnOffPayloadCommand to nil")
	}
	o.Set = true
	if err := o.Value.Decode(d); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptTurnOnOffPayloadCommand) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptTurnOnOffPayloadCommand) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes SentAt as json.
func (s SentAt) Encode(e *jx.Encoder) {
	unwrapped := time.Time(s)

	json.EncodeDateTime(e, unwrapped)
}

// Decode decodes SentAt from json.
func (s *SentAt) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode SentAt to nil")
	}
	var unwrapped time.Time
	if err := func() error {
		v, err := json.DecodeDateTime(d)
		unwrapped = v
		if err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "alias")
	}
	*s = SentAt(unwrapped)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s SentAt) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *SentAt) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *TurnOnOffPayload) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *TurnOnOffPayload) encodeFields(e *jx.Encoder) {
	{
		if s.Command.Set {
			e.FieldStart("command")
			s.Command.Encode(e)
		}
	}
	{
		if s.SentAt.Set {
			e.FieldStart("sentAt")
			s.SentAt.Encode(e)
		}
	}
}

var jsonFieldsNameOfTurnOnOffPayload = [2]string{
	0: "command",
	1: "sentAt",
}

// Decode decodes TurnOnOffPayload from json.
func (s *TurnOnOffPayload) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode TurnOnOffPayload to nil")
	}

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "command":
			if err := func() error {
				s.Command.Reset()
				if err := s.Command.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"command\"")
			}
		case "sentAt":
			if err := func() error {
				s.SentAt.Reset()
				if err := s.SentAt.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"sentAt\"")
			}
		default:
			return d.Skip()
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode TurnOnOffPayload")
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *TurnOnOffPayload) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *TurnOnOffPayload) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes TurnOnOffPayloadCommand as json.
func (s TurnOnOffPayloadCommand) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes TurnOnOffPayloadCommand from json.
func (s *TurnOnOffPayloadCommand) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode TurnOnOffPayloadCommand to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch TurnOnOffPayloadCommand(v) {
	case TurnOnOffPayloadCommandOn:
		*s = TurnOnOffPayloadCommandOn
	case TurnOnOffPayloadCommandOff:
		*s = TurnOnOffPayloadCommandOff
	default:
		*s = TurnOnOffPayloadCommand(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s TurnOnOffPayloadCommand) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *TurnOnOffPayloadCommand) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}
