// Code generated by agen, DO NOT EDIT.

package convertedstreetlights

import (
	"context"
)

// LightMeasured handles the "lightMeasured" operation.
//
// The message arrives from the "lightingMeasured" address.
type LightMeasuredHandler interface {
	LightMeasured(ctx context.Context, msg *LightMeasuredDotMessage) error
}

// TurnOnDotPublish handles the "turnOn.publish" operation.
//
// The message arrives from the "turnOn" address.
type TurnOnDotPublishHandler interface {
	TurnOnDotPublish(ctx context.Context, msg *TurnOnOff) error
}

// Handler handles all receive operations of the application.
type Handler interface {
	LightMeasured(ctx context.Context, msg *LightMeasuredDotMessage) error
	TurnOnDotPublish(ctx context.Context, msg *TurnOnOff) error
}

// SubscriberHandlers collects the handler of every receive operation.
type SubscriberHandlers struct {
	LightMeasured    LightMeasuredHandler
	TurnOnDotPublish TurnOnDotPublishHandler
}

// NewSubscriberHandlers builds SubscriberHandlers from per-operation handlers.
func NewSubscriberHandlers(
	h0 LightMeasuredHandler,
	h1 TurnOnDotPublishHandler,
) *SubscriberHandlers {
	return &SubscriberHandlers{
		LightMeasured:    h0,
		TurnOnDotPublish: h1,
	}
}

// NewHandler builds SubscriberHandlers from a single Handler implementing
// every receive operation.
func NewHandler(h Handler) *SubscriberHandlers {
	return &SubscriberHandlers{
		LightMeasured:    h,
		TurnOnDotPublish: h,
	}
}
