// Code generated by agen, DO NOT EDIT.

package convertedstreetlights

import (
	"context"

	"github.com/NefixEstrada/agen/runtime/broker"
)

// publishConfig carries options applied on top of a generated message.
type publishConfig struct {
	key     string
	headers map[string]string
}

// PublishOption customizes a single publish.
type PublishOption func(*publishConfig)

func newPublishConfig() *publishConfig {
	return &publishConfig{
		headers: map[string]string{},
	}
}

// WithKey sets the broker partition key of the published message.
func WithKey(key string) PublishOption {
	return func(c *publishConfig) {
		c.key = key
	}
}

// WithHeader sets an extra header on the published message.
func WithHeader(k, v string) PublishOption {
	return func(c *publishConfig) {
		c.headers[k] = v
	}
}

// Client publishes messages of the application's `send` operations to a
// broker via a runtime Publisher.
type Client struct {
	publisher broker.Publisher
}

// NewClient creates a Client publishing with the given Publisher.
func NewClient(publisher broker.Publisher) *Client {
	return &Client{
		publisher: publisher,
	}
}

// Close closes the underlying publisher.
func (c *Client) Close(ctx context.Context) error {
	return c.publisher.Close(ctx)
}

// TurnOnDotSubscribe publishes a message of the "turnOn.subscribe" operation.
func (c *Client) TurnOnDotSubscribe(ctx context.Context, msg TurnOnMessage, opts ...PublishOption) error {
	topic := TurnOnAddress
	out, err := encodeTurnOnDotSubscribeMessage(topic, msg, opts...)
	if err != nil {
		return err
	}
	return c.publisher.Publish(ctx, out)
}
