// Code generated by agen, DO NOT EDIT.

package convertedparams

import (
	"context"
)

// LightMeasured handles the "lightMeasured" operation.
//
// The message arrives from the "lightingMeasured/{parameter}/{parameter2}" address.
type LightMeasuredHandler interface {
	LightMeasured(ctx context.Context, msg *LightMeasuredDotMessage) error
}

// Handler handles all receive operations of the application.
type Handler interface {
	LightMeasured(ctx context.Context, msg *LightMeasuredDotMessage) error
}

// SubscriberHandlers collects the handler of every receive operation.
type SubscriberHandlers struct {
	LightMeasured LightMeasuredHandler
}

// NewSubscriberHandlers builds SubscriberHandlers from per-operation handlers.
func NewSubscriberHandlers(
	h0 LightMeasuredHandler,
) *SubscriberHandlers {
	return &SubscriberHandlers{
		LightMeasured: h0,
	}
}

// NewHandler builds SubscriberHandlers from a single Handler implementing
// every receive operation.
func NewHandler(h Handler) *SubscriberHandlers {
	return &SubscriberHandlers{
		LightMeasured: h,
	}
}
