// Code generated by agen, DO NOT EDIT.

package redisdemo

import (
	"github.com/NefixEstrada/agen/runtime/broker"
)

// Middleware wraps the raw message dispatch of the subscriber: it sees the
// raw broker.Incoming before decoding and the dispatch result after the typed
// handler ran.
//
//	mw := func(next broker.Handler) broker.Handler {
//		return func(ctx context.Context, raw broker.Incoming) error {
//			err := next(ctx, raw)
//			if err != nil {
//				// log, metric, ...
//			}
//			return err
//		}
//	}
//	sub := NewSubscriber(handlers, mw)
type Middleware = broker.Middleware

// DispatchHandler is a raw dispatch handler.
type DispatchHandler = broker.Handler
