// Code generated by agen, DO NOT EDIT.

package redisdemo

// OperationName is the agen operation name
type OperationName = string

const (
	ReceiveLightCommandOperation OperationName = "receiveLightCommand"
	SendLightCommandOperation    OperationName = "sendLightCommand"
)
