// Code generated by agen, DO NOT EDIT.

package redisdemo

import (
	"github.com/NefixEstrada/agen/runtime/agenerrors"
	"github.com/NefixEstrada/agen/runtime/broker"
	"github.com/go-faster/jx"
)

func decodeReceiveLightCommandMessage(raw broker.Incoming) (*LightCommand, error) {
	msg := new(LightCommand)
	{
		d := jx.DecodeBytes(raw.Body())
		if err := msg.Payload.Decode(d); err != nil {
			return nil, &agenerrors.DecodeMessageError{
				Operation: "receiveLightCommand",
				Message:   "lightCommand",
				Err:       err,
			}
		}
	}
	if err := msg.Validate(); err != nil {
		return nil, &agenerrors.ValidateMessageError{
			Operation: "receiveLightCommand",
			Message:   "lightCommand",
			Err:       err,
		}
	}
	return msg, nil
}
func encodeSendLightCommandMessage(topic string, msg *LightCommand, opts ...PublishOption) (broker.Outgoing, error) {
	if err := msg.Validate(); err != nil {
		return broker.Outgoing{}, &agenerrors.ValidateMessageError{
			Operation: "sendLightCommand",
			Message:   "lightCommand",
			Err:       err,
		}
	}
	cfg := newPublishConfig()
	for _, opt := range opts {
		opt(cfg)
	}
	out := broker.Outgoing{
		Topic:       topic,
		Key:         cfg.key,
		ContentType: "application/json",
		Headers:     cfg.headers,
	}
	{
		var e jx.Encoder
		msg.Payload.Encode(&e)
		out.Body = e.Bytes()
	}
	return out, nil
}
