// Code generated by agen, DO NOT EDIT.

package streetlights

// OperationName is the agen operation name
type OperationName = string

const (
	ReceiveLightMeasurementOperation OperationName = "receiveLightMeasurement"
	SendLightCommandOperation        OperationName = "sendLightCommand"
)
