// Code generated by agen, DO NOT EDIT.

package api

import (
	"github.com/NefixEstrada/agen/runtime/agenerrors"
	"github.com/NefixEstrada/agen/runtime/broker"
	"github.com/go-faster/jx"
)

func decodeLightMeasuredMessage(raw broker.Incoming) (*LightMeasuredDotMessage, error) {
	msg := new(LightMeasuredDotMessage)
	{
		d := jx.DecodeBytes(raw.Body())
		if err := msg.Payload.Decode(d); err != nil {
			return nil, &agenerrors.DecodeMessageError{
				Operation: "lightMeasured",
				Message:   "lightMeasured.message",
				Err:       err,
			}
		}
	}
	return msg, nil
}
