// Code generated by agen, DO NOT EDIT.

package convertedparams

import (
	"fmt"
)

// BuildLightingMeasured1Parameter1Parameter2Address builds the "lightingMeasured~1{parameter}~1{parameter2}" channel address from
// parameters.
// Parameter is the `parameter` channel address parameter.
// Parameter2 is the `parameter2` channel address parameter.
func BuildLightingMeasured1Parameter1Parameter2Address(parameter string, parameter2 string) (string, error) {
	return fmt.Sprintf("lightingMeasured/%s/%s", parameter, parameter2), nil
}
